# 1. Tomcat Server Setting
server:
  port: 80
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 인증서 파일 경로 <- keystore.p12를
    # src/main/resources밑에 뒀다면 경로 수정 X
    key-store-password: 111111
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    context-path: /
    encoding:
      charset: utf-8

# 2. SpringBoot Environment Setting
spring:
  springdoc:
    #    version: '@project.version@'
    api-docs:
      path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
      operations-sorter: alpha
      tags-sorter: alpha
      path: /swagger-ui.html
      disable-swagger-default-url: true
      display-query-params-without-oauth2: true
      doc-expansion: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stest?characterEncoding=utf8
    username: suser
    password: 111111
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  output:
    ansi:
      enabled: always

# 4. Logging Setting
logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
  #  error > info > debug

# 5. Application Environment Setting