# 1. Tomcat Server Setting
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # 인증서 파일 경로 <- keystore.p12를
    # src/main/resources밑에 뒀다면 경로 수정 X
    key-store-password: 111111
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    context-path: /
    encoding:
      charset: utf-8

# 2. SpringBoot Environment Setting
spring:
  datasource:
    #    url: jdbc:h2:~/tests
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: test
    password: 1111
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  output:
    ansi:
      enabled: always

# 4. Logging Setting
logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
  #  error > info > debug

# 5. Application Environment Setting